'use client';

import { useEffect, useMemo, useState } from 'react';
import { LocalizedText } from './language';
import { SiteHeader } from './site-header';

type Task = { id: string; title: string; type: 'copy' | 'scene' | 'review' | 'export'; done: boolean; approval: boolean };
type Snapshot = { id: string; createdAt: string; label: string; data: AgentState };
type AgentState = {
  projectName: string; objective: string; audience: string; owner: string; priority: 'low' | 'normal' | 'high' | 'urgent'; status: 'briefing' | 'making' | 'review' | 'ready';
  agentRole: string; outputFormat: string; sourceUrl: string; sourceNotes: string; trust: 'reference' | 'approved' | 'do-not-copy';
  visualDo: string; visualDont: string; memory: string; labels: string; safeZone: string; textScale: string; hookTempo: string; captionPosition: string; cameraRule: string; schedule: string;
  sourceChecked: boolean; altTextReady: boolean; humanReview: boolean; holdForAssets: boolean; shareReady: boolean; taskQueue: Task[];
};

const defaultAgent: AgentState = {
  projectName: '', objective: '', audience: '', owner: '', priority: 'normal', status: 'briefing',
  agentRole: 'Local video editing bot', outputFormat: '1080×1920 MP4 + captions + JSON handoff', sourceUrl: '', sourceNotes: 'Use only media and references that this workspace is allowed to use.', trust: 'reference',
  visualDo: 'Start with a clear hook. Keep captions readable. Use purposeful cuts.', visualDont: 'Do not copy another creator’s media, template, or private information.', memory: '', labels: '', safeZone: '10', textScale: '92', hookTempo: 'fast 0–1.0s', captionPosition: 'bottom safe zone', cameraRule: 'Use only the movement needed for the story', schedule: '',
  sourceChecked: false, altTextReady: false, humanReview: true, holdForAssets: false, shareReady: false,
  taskQueue: [
    { id: 'brief', title: 'Read the project contract and output schema', type: 'copy', done: false, approval: false },
    { id: 'scenes', title: 'Make Scene A and Scene B emotionally different', type: 'scene', done: false, approval: false },
    { id: 'packet', title: 'Fill the caption packet and Comment PROMPT', type: 'copy', done: false, approval: false },
    { id: 'review', title: 'Run visual, rights, and Gate A/B/C review', type: 'review', done: false, approval: true },
    { id: 'export', title: 'Prepare WebM export package for human approval', type: 'export', done: false, approval: true },
  ],
};

function readAgent<T>(key: string, fallback: T): T { try { const raw = window.localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } }
function badge(state: boolean, yes: string, no: string) { return <span className={`agent-badge ${state ? 'yes' : 'no'}`}>{state ? '✓ ' : '× '}{state ? yes : no}</span>; }

function loadAgent(): AgentState {
  const stored = readAgent<AgentState>('localVideoAgentDesk', defaultAgent);
  return { ...defaultAgent, ...stored, taskQueue: stored.taskQueue?.length ? stored.taskQueue : defaultAgent.taskQueue };
}

export default function AgentDesk() {
  const [agent, setAgent] = useState<AgentState>(loadAgent);
  const [snapshots, setSnapshots] = useState<Snapshot[]>(() => readAgent<Snapshot[]>('localVideoAgentSnapshots', []));
  const [newTask, setNewTask] = useState('');
  const [copied, setCopied] = useState('');
  useEffect(() => { window.localStorage.setItem('localVideoAgentDesk', JSON.stringify(agent)); window.localStorage.setItem('localVideoAgentSnapshots', JSON.stringify(snapshots.slice(0, 8))); }, [agent, snapshots]);
  const update = <K extends keyof AgentState>(key: K, value: AgentState[K]) => setAgent((current) => ({ ...current, [key]: value }));
  const completed = agent.taskQueue.filter((task) => task.done).length;
  const approvals = agent.taskQueue.filter((task) => task.approval).length;
  const completeness = [agent.projectName, agent.objective, agent.audience, agent.agentRole, agent.outputFormat, agent.visualDo, agent.visualDont, agent.memory, agent.labels, agent.sourceNotes, agent.schedule].filter(Boolean).length + [agent.sourceChecked, agent.altTextReady, agent.humanReview].filter(Boolean).length;
  const promptContract = useMemo(() => `You are ${agent.agentRole}.\n\nPROJECT: ${agent.projectName}\nGOAL: ${agent.objective}\nAUDIENCE: ${agent.audience}\nPRIORITY: ${agent.priority}\nOUTPUT: ${agent.outputFormat}\n\nEDITORIAL MEMORY:\n${agent.memory}\n\nVISUAL DO:\n${agent.visualDo}\n\nVISUAL DON'T:\n${agent.visualDont}\n\nEDIT RULES:\n- Safe zone: ${agent.safeZone}%\n- Text scale target: ${agent.textScale}%\n- Hook tempo: ${agent.hookTempo}\n- Caption position: ${agent.captionPosition}\n- Camera rule: ${agent.cameraRule}\n- Transition: hard cut only\n\nSOURCE POLICY:\n${agent.sourceNotes}\nSource status: ${agent.trust}\n\nRETURN ONLY:\n1. Scene A plan\n2. Scene B plan\n3. 10-second timing map\n4. Caption packet\n5. Gate risks\n6. Approval request when required`, [agent]);
  const manifest = useMemo(() => ({ schema: 'local-video-workspace.agent-handoff/v1', project: { name: agent.projectName, objective: agent.objective, audience: agent.audience, owner: agent.owner, priority: agent.priority, status: agent.status, schedule: agent.schedule }, agent: { role: agent.agentRole, output: agent.outputFormat, memory: agent.memory, labels: agent.labels.split(',').map((label) => label.trim()).filter(Boolean) }, source: { url: agent.sourceUrl, notes: agent.sourceNotes, trust: agent.trust, originalPostReupload: false }, edit: { safeZonePercent: Number(agent.safeZone), textScalePercent: Number(agent.textScale), hookTempo: agent.hookTempo, captionPosition: agent.captionPosition, cameraRule: agent.cameraRule, transition: 'hard_cut', audio: 'none | ig_safe | original' }, quality: { visualDo: agent.visualDo, visualDont: agent.visualDont, sourceChecked: agent.sourceChecked, altTextReady: agent.altTextReady, humanReviewRequired: agent.humanReview, shareReady: agent.shareReady }, queue: agent.taskQueue }), [agent]);
  const copy = async (kind: string, text: string) => { await navigator.clipboard?.writeText(text); setCopied(kind); window.setTimeout(() => setCopied(''), 1700); };
  const download = () => { const blob = new Blob([JSON.stringify(manifest, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'local-agent-handoff.json'; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 700); };
  const addTask = () => { const title = newTask.trim(); if (!title) return; update('taskQueue', [...agent.taskQueue, { id: `${Date.now()}`, title, type: 'review', done: false, approval: false }]); setNewTask(''); };
  const snapshot = () => setSnapshots((current) => [{ id: `${Date.now()}`, createdAt: new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date()), label: agent.projectName || 'Untitled project', data: agent }, ...current].slice(0, 8));
  return <><SiteHeader current="agent" /><main className="agent-main"><section className="agent-hero"><div><p className="kicker"><LocalizedText ko="Grok용 편집 콘솔" en="GROK-READY EDITING CONSOLE" zh="Grok 就绪编辑控制台" ja="Grok 対応編集コンソール" /></p><h1><LocalizedText ko="봇에게 빈 캔버스보다" en="Give a bot more than" zh="给机器人的不该只是" ja="ボットに手渡すのは" /><br /><span><LocalizedText ko="더 많은 맥락을 주세요." en="a blank canvas." zh="一张白纸。" ja="白紙のキャンバスだけじゃない。" /></span></h1><p><LocalizedText ko="브리프, 편집 규칙, 소스 범위, 승인, 기계가 읽을 수 있는 전달 정보를 하나의 지속적인 계약으로 관리합니다." en="One persistent contract for briefs, edit rules, source boundaries, approvals, and machine-readable handoff." zh="用一份持续更新的契约,统一管理简报、剪辑规则、素材边界、审批与机器可读的交接信息。" ja="ブリーフ、編集ルール、ソースの範囲、承認、機械可読な引き継ぎ情報を、ひとつの継続的な契約として管理します。" /></p></div><div className="agent-hero-stats"><article><b>{completeness} / 14</b><span><LocalizedText ko="계약 신호" en="contract signals" zh="契约信号" ja="契約シグナル" /></span></article><article><b>{completed} / {agent.taskQueue.length}</b><span><LocalizedText ko="완료된 작업" en="jobs complete" zh="已完成任务" ja="完了タスク" /></span></article><article><b>{approvals}</b><span><LocalizedText ko="사람 승인 게이트" en="human approval gates" zh="人工审批关卡" ja="人による承認ゲート" /></span></article><article><b>v{snapshots.length + 1}</b><span><LocalizedText ko="작업 버전" en="working version" zh="工作版本" ja="作業バージョン" /></span></article></div></section>
      <section className="agent-alert"><b>GROK HANDOFF READY</b><span>This desk creates a portable prompt contract and JSON manifest. It does not send data to Grok or Instagram by itself.</span>{badge(agent.humanReview, 'Human review required', 'Review bypassed')}</section>
      <section className="agent-grid identity-grid"><article className="agent-card span-2"><div className="agent-card-head"><span>01 · PROJECT CONTRACT</span><em>Machine-readable inputs</em></div><div className="field-grid four"><label>Project name<input value={agent.projectName} onChange={(event) => update('projectName', event.target.value)} /></label><label>Owner<input value={agent.owner} onChange={(event) => update('owner', event.target.value)} /></label><label>Priority<select value={agent.priority} onChange={(event) => update('priority', event.target.value as AgentState['priority'])}><option value="low">low</option><option value="normal">normal</option><option value="high">high</option><option value="urgent">urgent</option></select></label><label>Stage<select value={agent.status} onChange={(event) => update('status', event.target.value as AgentState['status'])}><option value="briefing">briefing</option><option value="making">making</option><option value="review">review</option><option value="ready">ready</option></select></label></div><label>Objective<textarea rows={3} value={agent.objective} onChange={(event) => update('objective', event.target.value)} /></label><label>Audience<input value={agent.audience} onChange={(event) => update('audience', event.target.value)} /></label><label>Labels <small>comma separated</small><input value={agent.labels} onChange={(event) => update('labels', event.target.value)} /></label></article>
        <article className="agent-card status-card"><div className="agent-card-head"><span>LIVE STATUS</span><em>Local only</em></div><div className="status-stack">{badge(agent.sourceChecked, 'Source reviewed', 'Source review pending')}{badge(agent.altTextReady, 'Alt text prepared', 'Alt text missing')}{badge(agent.humanReview, 'Human review on', 'Human review off')}{badge(agent.holdForAssets, 'Asset hold active', 'No asset hold')}{badge(agent.shareReady, 'Share approval granted', 'Share approval not granted')}</div><label className="switch-line"><input type="checkbox" checked={agent.sourceChecked} onChange={(event) => update('sourceChecked', event.target.checked)} /> Source reviewed</label><label className="switch-line"><input type="checkbox" checked={agent.altTextReady} onChange={(event) => update('altTextReady', event.target.checked)} /> Alt text ready</label><label className="switch-line"><input type="checkbox" checked={agent.holdForAssets} onChange={(event) => update('holdForAssets', event.target.checked)} /> Hold for assets</label><label className="switch-line"><input type="checkbox" checked={agent.shareReady} onChange={(event) => update('shareReady', event.target.checked)} /> Approve share</label></article></section>
      <section className="agent-grid"><article className="agent-card source-card"><div className="agent-card-head"><span>02 · SOURCE BOUNDARY</span><em>Rights before inspiration</em></div><label>Reference URL<input value={agent.sourceUrl} onChange={(event) => update('sourceUrl', event.target.value)} /></label><label>Source policy<textarea rows={4} value={agent.sourceNotes} onChange={(event) => update('sourceNotes', event.target.value)} /></label><label>Trust level<select value={agent.trust} onChange={(event) => update('trust', event.target.value as AgentState['trust'])}><option value="reference">reference only</option><option value="approved">approved source</option><option value="do-not-copy">do not copy</option></select></label><p className="agent-note">Original-post re-upload stays off. A bot may learn the hook, never the original asset.</p></article>
        <article className="agent-card visual-card"><div className="agent-card-head"><span>03 · EDIT CONTROL SURFACE</span><em>Specific enough to execute</em></div><div className="field-grid three"><label>Safe zone<input type="number" min="5" max="20" value={agent.safeZone} onChange={(event) => update('safeZone', event.target.value)} /></label><label>Text scale<input type="number" min="50" max="130" value={agent.textScale} onChange={(event) => update('textScale', event.target.value)} /></label><label>Hook tempo<select value={agent.hookTempo} onChange={(event) => update('hookTempo', event.target.value)}><option>fast 0–1.0s</option><option>medium 0–1.5s</option><option>slow 0–2.0s</option></select></label></div><label>Caption position<select value={agent.captionPosition} onChange={(event) => update('captionPosition', event.target.value)}><option>bottom safe zone</option><option>middle punchline</option><option>top header band</option></select></label><label>Camera rule<select value={agent.cameraRule} onChange={(event) => update('cameraRule', event.target.value)}><option>A push-in / B pull-out only</option><option>A push-in / B soft drift</option><option>A soft drift / B pull-out</option></select></label><label>Visual DO<textarea rows={3} value={agent.visualDo} onChange={(event) => update('visualDo', event.target.value)} /></label><label>Visual DON&apos;T<textarea rows={3} value={agent.visualDont} onChange={(event) => update('visualDont', event.target.value)} /></label></article></section>
      <section className="agent-grid"><article className="agent-card memory-card"><div className="agent-card-head"><span>04 · WORKING MEMORY</span><em>Carry intent between runs</em></div><label>Agent memory<textarea rows={7} value={agent.memory} onChange={(event) => update('memory', event.target.value)} /></label><label>Schedule window<input value={agent.schedule} onChange={(event) => update('schedule', event.target.value)} /></label><div className="memory-actions"><button onClick={() => update('memory', 'Start with the clearest hook, keep the edit focused, and avoid copied media or private information.')}>Reset to safe starter rule</button><button onClick={snapshot}>Save version snapshot</button></div></article>
        <article className="agent-card queue-card"><div className="agent-card-head"><span>05 · EDIT JOB QUEUE</span><em>{completed} complete · {approvals} need approval</em></div><div className="task-list">{agent.taskQueue.map((task, index) => <div className={`task-row ${task.done ? 'done' : ''}`} key={task.id}><button className="task-check" onClick={() => update('taskQueue', agent.taskQueue.map((item) => item.id === task.id ? { ...item, done: !item.done } : item))}>{task.done ? '✓' : String(index + 1).padStart(2, '0')}</button><div><b>{task.title}</b><small>{task.type}{task.approval ? ' · human approval' : ' · bot-safe task'}</small></div><button className="task-remove" aria-label={`Remove ${task.title}`} onClick={() => update('taskQueue', agent.taskQueue.filter((item) => item.id !== task.id))}>×</button></div>)}</div><div className="add-task"><input value={newTask} onChange={(event) => setNewTask(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') addTask(); }} placeholder="Add a job for the next bot run" /><button onClick={addTask}>Add</button></div></article></section>
      <section className="agent-grid handoff-grid"><article className="agent-card prompt-card"><div className="agent-card-head"><span>06 · GROK PROMPT CONTRACT</span><em>Copy, do not auto-send</em></div><pre>{promptContract}</pre><button className="agent-primary" onClick={() => copy('prompt', promptContract)}>{copied === 'prompt' ? 'Prompt copied' : 'Copy Grok prompt contract'}</button></article><article className="agent-card manifest-card"><div className="agent-card-head"><span>07 · JSON HANDOFF</span><em>Portable job state</em></div><pre>{JSON.stringify(manifest, null, 2)}</pre><div className="manifest-actions"><button onClick={() => copy('json', JSON.stringify(manifest, null, 2))}>{copied === 'json' ? 'JSON copied' : 'Copy JSON'}</button><button onClick={download}>Download JSON</button></div></article></section>
      <section className="agent-card snapshot-card"><div className="agent-card-head"><span>08 · VERSION MEMORY</span><em>Last {snapshots.length} local snapshots</em></div>{snapshots.length ? <div className="snapshot-list">{snapshots.map((item, index) => <div key={item.id}><span>v{snapshots.length - index}</span><b>{item.label}</b><small>{item.createdAt}</small><button onClick={() => setAgent(item.data)}>Restore</button></div>)}</div> : <p className="agent-note">No snapshot yet. Save a version before handing the contract to another bot.</p>}</section>
      <section className="agent-feature-register"><p className="kicker">FEATURE REGISTER</p><h2>30+ editable signals for a future Grok run.</h2><div>{['Project contract', 'Owner', 'Priority', 'Stage', 'Audience', 'Labels', 'Source URL', 'Trust level', 'Source policy', 'Source review', 'Safe zone', 'Text scale', 'Hook tempo', 'Caption position', 'Camera rule', 'Visual DO', 'Visual DON’T', 'Working memory', 'Schedule', 'Asset hold', 'Alt text state', 'Human review', 'Share approval', 'Job queue', 'Job completion', 'Approval jobs', 'Prompt contract', 'JSON manifest', 'JSON download', 'Snapshots', 'Restore version'].map((feature, index) => <span key={feature}>{String(index + 1).padStart(2, '0')} {feature}</span>)}</div></section>
    </main><footer className="forge-footer"><span>Local video workspace</span><span>Agent-ready editorial contract · local-first</span><span>Runs on this device</span></footer></>;
}
