'use client';

import { ChangeEvent, useEffect, useState } from 'react';
import { LocalizedText } from './language';
import { SiteHeader } from './site-header';

type Clip = { id: string; start: number; end: number; text: string; speaker: string; keep: boolean };
type SourceMeta = { name: string; duration: number; width: number; height: number; size: number };
type Gate = { name: string; pass: boolean; detail: string };

const defaultTranscript = `[00:00.00 - 00:01.15] S0 um, the AI wrote a whole novel
[00:01.80 - 00:03.65] S0 when I asked for a six-line email
[00:04.10 - 00:06.20] S0 so I gave it one rule instead
[00:06.45 - 00:09.80] S0 subject, one ask, and no greeting essay`;

const initialClips: Clip[] = [
  { id: 'c1', start: 0, end: 1.15, text: 'um, the AI wrote a whole novel', speaker: 'S0', keep: false },
  { id: 'c2', start: 1.8, end: 3.65, text: 'when I asked for a six-line email', speaker: 'S0', keep: true },
  { id: 'c3', start: 4.1, end: 6.2, text: 'so I gave it one rule instead', speaker: 'S0', keep: true },
  { id: 'c4', start: 6.45, end: 9.8, text: 'subject, one ask, and no greeting essay', speaker: 'S0', keep: true },
];

function format(seconds: number) {
  const min = Math.floor(seconds / 60); const sec = seconds - min * 60;
  return `${String(min).padStart(2, '0')}:${sec.toFixed(2).padStart(5, '0')}`;
}
function parseTime(value: string) {
  const parts = value.trim().split(':').map(Number); if (parts.some(Number.isNaN)) return 0;
  return parts.length === 2 ? parts[0] * 60 + parts[1] : parts.length === 3 ? parts[0] * 3600 + parts[1] * 60 + parts[2] : 0;
}
function hasFiller(text: string) { return /(^|\s)(um+|uh+|erm+|like|you know)([,.!]?)(\s|$)/i.test(text); }
function twoWordCaption(text: string) { return (text.match(/[A-Za-z0-9']+/g) ?? []).slice(0, 2).join(' ').toUpperCase() || 'VIDEO'; }
function saveDownload(name: string, content: string, type = 'application/json') {
  const blob = new Blob([content], { type }); const url = URL.createObjectURL(blob); const link = document.createElement('a');
  link.href = url; link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 700);
}
function readSaved<T>(key: string, fallback: T): T { try { const raw = window.localStorage.getItem(key); return raw ? JSON.parse(raw) as T : fallback; } catch { return fallback; } }
function parseTranscript(raw: string) {
  return raw.split(/\r?\n/).map((line, index) => {
    const match = line.match(/^\s*\[(.+?)\s*-\s*(.+?)\]\s*(?:(S\d+)\s*)?(.*)$/i);
    if (!match) return null;
    const start = parseTime(match[1]); const end = parseTime(match[2]); const text = match[4].trim();
    return end > start && text ? { id: `t-${index}-${start}`, start, end, text, speaker: match[3] ?? 'S0', keep: !hasFiller(text) } as Clip : null;
  }).filter((clip): clip is Clip => Boolean(clip));
}

function buildMoviePy(clips: Clip[], sourceName: string) {
  const active = clips.filter((clip) => clip.keep).map((clip) => [Number(clip.start.toFixed(2)), Number(clip.end.toFixed(2)), twoWordCaption(clip.text)]);
  return `# Generated by Local Video Workspace Cut Log — local-only\n# Requires MoviePy 2: pip install moviepy\nfrom moviepy import VideoFileClip, TextClip, CompositeVideoClip, concatenate_videoclips, afx\n\nSOURCE = r"${sourceName || 'replace-with-your-source.mp4'}"\nOUTPUT = "final-video.mp4"\nEDL = ${JSON.stringify(active, null, 2)}\n\ndef captioned(clip, caption):\n    title = (TextClip(\n        font="Arial", text=caption, font_size=78, color="white",\n        stroke_color="black", stroke_width=3, size=(920, None), method="caption"\n    ).with_duration(clip.duration).with_position(("center", 1480)))\n    return CompositeVideoClip([clip, title], size=(1080, 1920))\n\nwith VideoFileClip(SOURCE) as source:\n    cuts = []\n    for start, end, caption in EDL:\n        cut = source.subclipped(start, end).with_effects([\n            afx.AudioFadeIn(0.03), afx.AudioFadeOut(0.03)\n        ])\n        cuts.append(captioned(cut, caption))\n    final = concatenate_videoclips(cuts, method="compose")\n    final.write_videofile(OUTPUT, fps=30, codec="libx264", audio_codec="aac")\n`;
}

export default function CutLab() {
  const [source, setSource] = useState<SourceMeta | null>(null); const [sourceUrl, setSourceUrl] = useState(''); const [transcript, setTranscript] = useState(defaultTranscript); const [clips, setClips] = useState<Clip[]>(initialClips); const [silence, setSilence] = useState(0.45); const [approved, setApproved] = useState(false); const [copied, setCopied] = useState(''); const [loaded, setLoaded] = useState(false);
  useEffect(() => { const saved = readSaved<{ transcript: string; clips: Clip[]; silence: number; approved: boolean }>('localVideoCutLog', { transcript: defaultTranscript, clips: initialClips, silence: .45, approved: false }); const timer = window.setTimeout(() => { setTranscript(saved.transcript); setClips(saved.clips?.length ? saved.clips : initialClips); setSilence(saved.silence); setApproved(saved.approved); setLoaded(true); }, 0); return () => window.clearTimeout(timer); }, []);
  useEffect(() => { if (loaded) window.localStorage.setItem('localVideoCutLog', JSON.stringify({ transcript, clips, silence, approved })); }, [transcript, clips, silence, approved, loaded]);
  useEffect(() => () => { if (sourceUrl) URL.revokeObjectURL(sourceUrl); }, [sourceUrl]);

  const kept = clips.filter((clip) => clip.keep); const total = kept.reduce((sum, clip) => sum + clip.end - clip.start, 0); const sourceDuration = source?.duration || Math.max(10, ...clips.map((clip) => clip.end));
  const gaps = clips.slice(1).map((clip, index) => ({ after: clips[index], before: clip, gap: Math.max(0, clip.start - clips[index].end) })).filter((item) => item.gap >= silence);
  const qc: Gate[] = [
    { name: 'Transcript-first cut', pass: kept.length > 0 && kept.every((clip) => clip.end > clip.start), detail: kept.length ? `${kept.length} spoken segments retained.` : 'Keep at least one spoken segment.' },
    { name: 'Dead-space audit', pass: gaps.length === 0, detail: gaps.length ? `${gaps.length} pause${gaps.length > 1 ? 's' : ''} exceed ${silence.toFixed(2)}s.` : 'No selected transcript gap exceeds the threshold.' },
    { name: 'Cut boundary audio', pass: kept.length < 2 || kept.every((clip, index) => index === 0 || clip.start >= kept[index - 1].end), detail: kept.length < 2 ? 'Add a second clip to inspect transitions.' : 'Every transition receives a 30ms fade in the local render recipe.' },
    { name: 'Strategy approval', pass: approved, detail: approved ? 'You approved this edit decision before render.' : 'Approve the strategy before exporting a MoviePy recipe.' },
  ];
  const allGreen = qc.every((gate) => gate.pass); const edl = { schema: 'local-video-workspace.offline-edl/v1', mode: 'local_only', source, silenceThresholdSeconds: silence, audioFadeMilliseconds: 30, captionStyle: '2-word uppercase', clips: kept.map((clip) => ({ in: clip.start, out: clip.end, duration: Number((clip.end - clip.start).toFixed(2)), caption: twoWordCaption(clip.text), speaker: clip.speaker })), approval: approved, qc };

  const loadVideo = (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; if (sourceUrl) URL.revokeObjectURL(sourceUrl); const url = URL.createObjectURL(file); const video = document.createElement('video'); video.preload = 'metadata'; video.onloadedmetadata = () => { setSource({ name: file.name, duration: video.duration, width: video.videoWidth, height: video.videoHeight, size: file.size }); setSourceUrl(url); }; video.src = url; };
  const updateClip = (id: string, field: keyof Clip, value: string | boolean) => setClips((items) => items.map((clip) => clip.id === id ? { ...clip, [field]: typeof value === 'string' && (field === 'start' || field === 'end') ? Math.max(0, Number(value)) : value } : clip));
  const rebuild = () => { const next = parseTranscript(transcript); if (next.length) setClips(next); };
  const addMarker = () => setClips((items) => [...items, { id: `m-${Date.now()}`, start: Math.max(0, sourceDuration - 1), end: sourceDuration, text: 'New clip — edit caption', speaker: 'S0', keep: true }]);
  const copy = async (name: string, value: string) => { await navigator.clipboard?.writeText(value); setCopied(name); window.setTimeout(() => setCopied(''), 1600); };

  return <><SiteHeader current="cut" />
    <main className="cut-main"><section className="cut-hero"><div><p className="kicker"><LocalizedText ko="로컬 비디오 컷 로그" en="LOCAL VIDEO CUT LOG" zh="本地视频剪辑记录" ja="ローカル動画カットログ" /></p><h1><LocalizedText ko="테이크를 읽고." en="Read the take." zh="读懂这条素材," ja="テイクを読み、" /><br /><span><LocalizedText ko="필요한 부분만 자르세요." en="Then cut it." zh="然后精准剪切。" ja="必要な部分だけをカット。" /></span></h1><p><LocalizedText ko="대본 우선 편집, 정밀 EDL, 30ms 컷 페이드, 두 단어 자막, 로컬 MoviePy 레시피를 제공합니다. 원본 파일은 이 기기에만 남습니다." en="Transcript-first editing, a precise EDL, 30ms cut fades, two-word captions, and a local MoviePy recipe. Your source file stays on this device." zh="提供以文字稿为先的剪辑、精确的 EDL、30ms 转场淡入淡出、双词字幕和本地 MoviePy 方案。你的源文件只留在这台设备上。" ja="文字起こし優先の編集、精密な EDL、30ms のカットフェード、2 単語ずつの字幕、ローカル MoviePy レシピを提供します。ソースファイルはこの端末だけに残ります。" /></p></div><div className="cut-stats"><article><b>{source ? format(source.duration) : '—'}</b><span><LocalizedText ko="원본 길이" en="source duration" zh="原片时长" ja="元の長さ" /></span></article><article><b>{format(total)}</b><span><LocalizedText ko="유지 길이" en="kept duration" zh="保留时长" ja="採用した長さ" /></span></article><article><b>{gaps.length}</b><span><LocalizedText ko="무음 구간 표시" en="pause flags" zh="静音区间标记" ja="無音区間フラグ" /></span></article><article><b>{allGreen ? <LocalizedText ko="준비됨" en="READY" zh="就绪" ja="準備完了" /> : <LocalizedText ko="검토" en="REVIEW" zh="待审核" ja="要確認" />}</b><span><LocalizedText ko="렌더 상태" en="render state" zh="渲染状态" ja="レンダー状態" /></span></article></div></section>
      <section className="cut-note"><b>OFFLINE SOURCE INTAKE</b><span>Choose a local file to preview its metadata. This workspace does not upload it, retain the file after the tab closes, or send it to a provider.</span></section>
      <section className="cut-grid intake-grid"><article className="cut-card source-card-local"><div className="cut-card-head"><span>01 · SOURCE TAKE</span><em>Local file only</em></div><label className="source-drop">Choose a video file<input type="file" accept="video/*" onChange={loadVideo} /><small>{source ? `${source.name} · ${format(source.duration)} · ${source.width}×${source.height}` : 'MP4, WebM, or a browser-readable local video'}</small></label>{sourceUrl ? <video className="local-video" controls src={sourceUrl} /> : <div className="source-empty">No file loaded. You can still build an edit decision list from the transcript.</div>}</article><article className="cut-card transcript-card"><div className="cut-card-head"><span>02 · TRANSCRIPT LEDGER</span><em>Word boundaries before cuts</em></div><label>Timestamped lines<textarea rows={9} value={transcript} onChange={(event) => setTranscript(event.target.value)} /></label><div className="cut-actions"><button onClick={rebuild}>Build cut list from transcript</button><button onClick={() => setTranscript(defaultTranscript)}>Load starter example</button></div><p>Format: <code>[00:00.00 - 00:01.50] S0 spoken text</code>. Filler-word lines start disabled for review.</p></article></section>
      <section className="cut-card decision-card"><div className="cut-card-head"><span>03 · EDIT DECISION LIST</span><em>{kept.length} kept · {format(total)} total</em></div><div className="decision-controls"><label>Pause flag threshold<input type="range" min="0.15" max="1.5" step="0.05" value={silence} onChange={(event) => setSilence(Number(event.target.value))} /><output>{silence.toFixed(2)}s</output></label><button onClick={addMarker}>Add clip</button><span>Green = keep · amber = review filler · red gap = dead-space flag</span></div><div className="edl-list">{clips.map((clip, index) => { const previous = clips[index - 1]; const gap = previous ? clip.start - previous.end : 0; return <div className={`edl-row ${clip.keep ? 'keep' : 'drop'}`} key={clip.id}>{previous && gap >= silence && <i className="dead-gap">{format(gap)} pause</i>}<label className="edl-toggle"><input type="checkbox" checked={clip.keep} onChange={(event) => updateClip(clip.id, 'keep', event.target.checked)} />{clip.keep ? 'KEEP' : 'CUT'}</label><label>IN<input type="number" min="0" step=".05" value={clip.start} onChange={(event) => updateClip(clip.id, 'start', event.target.value)} /></label><label>OUT<input type="number" min="0" step=".05" value={clip.end} onChange={(event) => updateClip(clip.id, 'end', event.target.value)} /></label><div><b>{clip.text}</b><small>{clip.speaker} · caption: {twoWordCaption(clip.text)}{hasFiller(clip.text) ? ' · filler detected' : ''}</small></div><button aria-label={`Remove clip ${index + 1}`} onClick={() => setClips((items) => items.filter((item) => item.id !== clip.id))}>×</button></div>; })}</div><div className="cut-timeline">{clips.map((clip) => <span key={`track-${clip.id}`} className={clip.keep ? 'active' : ''} style={{ left: `${clip.start / sourceDuration * 100}%`, width: `${Math.max(2, (clip.end - clip.start) / sourceDuration * 100)}%` }}>{clip.keep ? twoWordCaption(clip.text) : 'CUT'}</span>)}</div></section>
      <section className="cut-grid qc-grid"><article className="cut-card qc-card"><div className="cut-card-head"><span>04 · CUT-BOUNDARY SELF CHECK</span><em>Before render</em></div><div className="qc-list">{qc.map((gate) => <div className={gate.pass ? 'pass' : 'fail'} key={gate.name}><b>{gate.pass ? '✓' : '×'}</b><span><strong>{gate.name}</strong>{gate.detail}</span></div>)}</div><label className="approval-line"><input type="checkbox" checked={approved} onChange={(event) => setApproved(event.target.checked)} /> I approve this local cut strategy before creating a render recipe.</label></article><article className="cut-card export-recipe"><div className="cut-card-head"><span>05 · LOCAL RENDER HANDOFF</span><em>EDL + MoviePy 2</em></div><p>Export the EDL for any local editor, or generate a MoviePy 2 script for local subclips, caption overlays, compositing, and 30ms audio fades.</p><div className="cut-actions"><button onClick={() => saveDownload('local-edit-decision-list.json', JSON.stringify(edl, null, 2))}>Download EDL JSON</button><button disabled={!approved} onClick={() => saveDownload('local-render.py', buildMoviePy(clips, source?.name ?? 'replace-with-your-source.mp4'), 'text/x-python')}>Download MoviePy recipe</button><button onClick={() => void copy('recipe', buildMoviePy(clips, source?.name ?? 'replace-with-your-source.mp4'))}>{copied === 'recipe' ? 'Recipe copied' : 'Copy MoviePy recipe'}</button></div><pre>{buildMoviePy(kept, source?.name ?? 'replace-with-your-source.mp4')}</pre></article></section>
      <section className="cut-register"><p className="kicker">ADAPTED FOR LOCAL EDITING</p><h2>Source → transcript → EDL → review → render.</h2><div><span>Local file intake</span><span>Transcript ledger</span><span>Filler-word review</span><span>Silence flags</span><span>Clip in/out</span><span>Two-word captions</span><span>30ms cut fades</span><span>EDL export</span><span>MoviePy 2 recipe</span><span>Manual approval</span><span>Persistent cut log</span><span>No API</span></div></section>
    </main><footer className="forge-footer"><span>Local video workspace</span><span>Local source analysis · local render handoff</span><span>Runs on this device</span></footer></>;
}
